version: "3"
services:
  master:
    image: mysql:debian
    container_name: master
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwert
      MYSQL_DATABASE: primerBD
      POSTGRES_USER: master
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: primerBD
    volumes:
      - ./master-scripts:/docker-entrypoint-initdb.d
    networks:
      db-network:
        ipv4_address: 172.16.0.2


  slave1:
    image: mysql:debian
    container_name: slave1
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwert
      MYSQL_MASTER_HOST: master
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: qwert
      POSTGRES_USER: slave1
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: primerBD
    networks:
      db-network:
        ipv4_address: 172.16.0.3



  slave2:
    image: mysql:debian
    container_name: slave2
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwert
      MYSQL_MASTER_HOST: master
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: qwert
      POSTGRES_USER: slave2
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: primerBD
    networks:
      db-network:
        ipv4_address: 172.16.0.4


networks:
  db-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
